config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Defines the root path route ("/")
  # As a visitor I can visit the home page
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # As a visitor I can browse through flats

  resources :flats, only: %i[index show new create] do
    resources :bookings, only: %i[new create]
  end
  # As a user I can create a rating of a flat
  resources :bookings, only: [] do
    resources :ratings, only: :create
  end

  resources :users, only: [:show] do
    resources :bookings, only: [:index, :show]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
  has_one :rating, dependent: :destroy
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many_attached :photos
  belongs_to :user
  has_many :bookings
  has_many :ratings, through: :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model

  def average_rating
    unless ratings.empty?
      flat_ratings = ratings.map { |rating| rating.rating }
      flat_ratings.sum.to_f / flat_ratings.count
    end
  end

  pg_search_scope :global_search,
    against: [ :name, :location, :description ],
    using: {
      tsearch: { prefix: true }
    }

  def leaf_count
    if carbon_footprint < 29
      3
    elsif carbon_footprint < 49
      2
    else
      1
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flats
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :location, :about])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :location, :about])
  end

  def after_sign_in_path_for(resource)
    user_path(@user, redir_param: 21, accord_param: "flush-headingTwo") # your path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def create
    start_date = Date.new(
      params[:booking]["start_date(1i)"].to_i,
      params[:booking]["start_date(2i)"].to_i,
      params[:booking]["start_date(3i)"].to_i
    )
    end_date = Date.new(
      params[:booking]["end_date(1i)"].to_i,
      params[:booking]["end_date(2i)"].to_i,
      params[:booking]["end_date(3i)"].to_i
    )

    flat = Flat.find(params[:flat_id])
    price = (end_date - start_date)*(flat.price_per_night)

    @booking = Booking.new(
      start_date: start_date,
      end_date: end_date,
      user: current_user,
      flat: flat,
      total_price: price
    )

    @booking.save
    redirect_to user_path(current_user, redir_param: 21, accord_param: "flush-headingTwo"), notice: "Booking completed"
  end

  def show
    @booking = Booking.find(params[:id])
    @user = User.find(params[:user_id])
    @role = role(@user)
    @redir = params[:redir_param].nil? ? 0 : params[:redir_param].to_i
  end

  private

  def role(puser)
    return puser.host ? "Host" : "Guest"
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
    if params[:query].present?
      @flats = Flat.global_search(params[:query])
    end
    if params[:sort] == "rating"
      flats_with_ratings = @flats.select { |flat| flat.average_rating }
      flats_without_ratings = @flats.select { |flat| !flat.average_rating }
      flats_with_ratings = flats_with_ratings.sort_by { |flat| -flat.average_rating }
      @flats = flats_with_ratings + flats_without_ratings
    elsif params[:sort] == "price_asc"
      @flats = @flats.sort_by { |flat| flat.price_per_night }
    elsif params[:sort] == "price_desc"
      @flats = @flats.sort_by { |flat| flat.price_per_night }.reverse
    elsif params[:sort] == "carbon_footprint"
      @flats = @flats.sort_by { |flat| flat.carbon_footprint }
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @rating = Rating.new
    @booking = Booking.new
    @bookings_with_reviews = Booking.joins(:rating)
    @past_bookings = @flat.bookings.where(user: current_user, end_date: ..1.day.ago) - @bookings_with_reviews
    @marker = [{ lat: @flat.latitude, lng: @flat.longitude }]
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    @flat.carbon_footprint = rand(10..70)
    @flat.save!
    redirect_to flat_path(@flat)
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :description, :price_per_night, :location, :capacity, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @flats_with_best_carbon_footprint = Flat.where(carbon_footprint: 0..30)
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def create
    @rating = Rating.new(rating_params)
    @booking = Booking.find(params[:booking_id])
    @rating.booking = @booking
    if @rating.save
      redirect_to flat_path(@booking.flat)
    else
      @booking = Booking.new
      render "flats/show", status: :unprocessable_entity
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
require 'date'

class UsersController < ApplicationController

    def show
      @user = User.find(params[:id])
      @role = role(@user)
      @redir = params[:redir_param].nil? ? 0 : params[:redir_param].to_i
      # booking
      @bookings_current = @user.bookings.where('end_date > ? ', Date.today)
      @bookings_historic = @user.bookings.where('end_date <= ? ', Date.today)
      # orders
      @orders_current =  Booking.joins(:flat).where('flats.user_id = ? ', @user.id).where('bookings.end_date > ? ', Date.today)
      @orders_historic =  Booking.joins(:flat).where('flats.user_id = ? ', @user.id).where('bookings.end_date <= ? ', Date.today)
      # empties? 
      @bookings_current_exist = @bookings_current.count > 0 ? true : false
      @bookings_historic_exist = @bookings_historic.count > 0 ? true : false
      @orders_current_exist = @orders_current.count > 0 ? true : false
      @orders_historic_exist = @orders_historic.count > 0 ? true : false

       end
   
    private

    def role(puser)
       return puser.host ? "Host" : "Guest"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sort_arrow(sort_param)
    if sort_param == "price_asc"
      "<i class='fa-solid fa-arrow-up'></i>"
    elsif sort_param == "price_desc"
      "<i class='fa-solid fa-arrow-down'></i>"
    end
  end
end

app/views/bookings/show.html.erb
 <div class="container-fluid">
   <div class="row flex-nowrap">
        <!--SIDEBAR -->
     <%# Booker %>
     <% content_for(:booker) { render partial: 'users/sidebar_booker' } %>
     <%# Host %>
     <% if  (@role == 'Host')%>
     <% content_for(:host) { render partial: 'users/sidebar_host' } %>
     <% end%>
     <%= render  "users/navbar" %>
     <!--CONTENT -->
  <div class="col py-3">
  <div class="container" style="margin-top: 12px">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <!--CARD ITERATION -->
      <div class="col">
          <%# Tabs %>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
             <li class="nav-item" role="presentation">
               <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#booking" type="button" role="tab" aria-controls="booking" aria-selected="true">Your booking</button>
            </li>
            <li class="nav-item" role="presentation">
               <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#hotel" type="button" role="tab" aria-controls="hotel" aria-selected="false">Your Hotel</button>
            </li>
            <li class="nav-item" role="presentation">
               <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#host" type="button" role="tab" aria-controls="host" aria-selected="false">Your host</button>
           </li>
        </ul>
       <div class="tab-content" id="myTabContent">
       <div class="tab-pane fade show active" id="booking" role="tabpanel" aria-labelledby="home-tab">
           <div class="card h-200">
              <h5>Booking-Nr.: <%= @booking.id %></h5>
              <div class="card-body">
              <p>booked by: <%= @booking.user.name %></p>
              <p>Unit: <%= @booking.flat.name %></p>
              <p>Location: <%= @booking.flat.location %></p>
              <p>from <%= @booking.start_date %></p>
              <p>to <%= @booking.end_date %></p>
              <p>nights: <%= (@booking.end_date - @booking.start_date).to_i %></p>
              <p>Total: <%= "#{@booking.total_price} €" %></p>
              <p>your Host: <%= @booking.flat.user.name %></p>
              <li class="list-group-item">Booking confirmed: <%= @booking.confirmed  ? '<i class="fa-solid fa-check text-success"></i>'.html_safe : '<i class="fa-solid fa-xmark text-danger"></i>'.html_safe %></li>
              </div>
              </div>
       </div>
       <div class="tab-pane fade" id="hotel" role="tabpanel" aria-labelledby="profile-tab">
       <div class="card h-200">
           <%= cl_image_tag @booking.flat.photos.first.key, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to @booking.flat.name, flat_path(@booking.flat) %></h5>
             <li class="list-group-item"><%= @booking.flat.location %></li>
            <p class="card-text"><%= @booking.flat.description %></p>
            <div class="leaves_index align-items-center"><%= '<i class="fa-solid fa-leaf"></i>'.html_safe * @booking.flat.leaf_count %></div> 
          </div>
        </div>
        </div>
       <div class="tab-pane fade" id="host" role="tabpanel" aria-labelledby="profile-tab">
            <div class="card h-200">
            <h5>Your host.: <%= @booking.flat.user.name %></h5>
            <div class="card-body">
            <a href= "<%= @booking.flat.user.email %>"><%= @booking.flat.user.email %></a>
            <p class="card-text"><%=  @booking.flat.user.location %></p>
            </div>
            </div>
        </div>
      </div>              
  </div>
</div>
       </div>
     </div>
   </div>
</div>  

app/views/flats/_top-cb.html.erb
<!--CARDS -->
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
    <% flats_with_best_carbon_footprint.each do |flat| %>
      <div class="col">
        <div class="card h-100">
          <%= cl_image_tag flat.photos.first.key, height: 300, width: 400, crop: :fill, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <div class="d-flex">
              <h5 class="card-title align-items-center"><%= link_to flat.name, flat_path(flat) %></h5>
              <div class="leaves_index align-items-center"><%= '<i class="fa-solid fa-leaf"></i>'.html_safe * flat.leaf_count %></div>
            </div>
            <p class="card-text text-truncate"><%= flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{flat.price_per_night} €" %></p>
              <p> Capacity: <%= flat.capacity %> </p>
              <p><i class="fa-regular fa-star"></i><%= flat.average_rating&.truncate(1) %> (<%= flat.ratings.count%>)</p>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<!--SORTING BUTTONS -->
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center">
    <h2>Sort by:</h2>
    <%= link_to "Rating", flats_path(sort: "rating"), class: "btn btn-secondary"%>
    <%= link_to "Price #{sort_arrow(params[:sort])}".html_safe, flats_path(sort: params[:sort] == "price_asc" ? "price_desc" : "price_asc"), class: "btn btn-secondary"%>
    <%= link_to "Carbon Footprint", flats_path(sort: "carbon_footprint"), class: "btn btn-secondary"%>
  </div>
</div>

<!--CARDS -->
<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
    <% @flats.each do |flat| %>
      <div class="col">
        <div class="card h-100">
          <%= cl_image_tag flat.photos.first.key, height: 300, width: 400, crop: :fill, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <div class="d-flex">
              <h5 class="card-title align-items-center"><%= link_to flat.name, flat_path(flat) %></h5>
              <div class="leaves_index align-items-center"><%= '<i class="fa-solid fa-leaf"></i>'.html_safe * flat.leaf_count %></div>
            </div>
            <p class="card-text text-truncate"><%= flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{flat.price_per_night} €" %></p>
              <p> Capacity: <%= flat.capacity %> </p>
              <p><i class="fa-regular fa-star"></i><%= flat.average_rating&.truncate(1) %> (<%= flat.ratings.count%>)</p>
            </li>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <h2>Create your flat</h2>
  <%= simple_form_for(@flat) do |f| %>
    <div class="form-inputs">
      <%= f.input :name,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "name" }%>
      <%= f.input :description,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "description" }%>
      <%= f.input :price_per_night,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "price_per_night" }%>
      <%= f.input :location,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "location" }%>
      <%= f.input :capacity,
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "capacity" }%>
      <%= f.input :photos, as: :file, input_html: { multiple: true } %>

    </div>

    <%= f.submit "Create a flat", class: "btn btn-flat" %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Carbonbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="turbo-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <!-- GEOCODING -->
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">

  <!--NAVBAR -->
  <%= render "devise/shared/flashes" %>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <%= link_to root_path do %>
        <%= image_tag "logo.png", class: "company-logo" %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <%if user_signed_in?  %>
          <li class="nav-item">
            <%= link_to "Become a host", new_flat_path, class: "btn btn-secondary" %>
          </li>
          <%end  %>
        </ul>

          <%= form_with url: flats_path, method: :get, class: "d-flex", id: "navsearch" do %>
            <%= text_field_tag :query,
              params[:query],
              class: "form-control me-2",
              placeholder: "Find a flat"
            %>
            <%= submit_tag "Search", class: "btn btn-outline-secondary" %>
          <% end %>

        <% if user_signed_in? %>
          <div class="nav-item dropdown">
            <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </div>
        <% else %><div class="d-grid gap-2 d-md-block">
          <%= link_to "Login", new_user_session_path, class: "btn btn-secondary" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-flat" %>
        </div>
        <% end %>
      </div>
    </div>
  </nav>

  <!--YIELD -->
  <div class="flex-grow-1">
    <%= yield %>
  </div>

  <!--FOOTER -->
  <div class="footer">
    <div class="footer-links">
      <a id="Paul" href="https://github.com/paultilly"><i class="fab fa-github" ></i></a>
      <a id="Markus" href="https://github.com/MNicehouse"><i class="fab fa-github" ></i></a>
      <a id="Sascha" href="https://github.com/sascha-belski"><i class="fab fa-github" ></i></a>
      <a id="Chris" href="https://github.com/ValuableRow"><i class="fab fa-github" ></i></a>
    </div>
      <div class="footer-copyright">
        Made with <i class="fas fa-heart"></i> at Le Wagon
    </div>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner-home" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/random/1440×1024/?house);">
  <div class="container">
    <h1>Carbonbnb helps you find great flats with minimal carbon footprint during your trips</h1>
    <p>Give back to mother earth while on the road</p>
    <%= link_to "Browse flats", "/flats", class: "btn btn-flat" %>
  </div>
</div>

<div class="container">
    <h3 class="mb-4 mt-4">Our flats with the best carbon footprint</h3>
    <%= render 'flats/top-cb', flats_with_best_carbon_footprint: @flats_with_best_carbon_footprint %>
</div>

app/views/users/_bookingcard.html.erb
<div class="container">
  <p>current bookings:</p>
  <% if @bookings_current_exist %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
    <% @bookings_current.each do |booking| %>
      <div class="col">
      <a href="<%= user_booking_path( @user, booking, redir_param: 21, accord_param: "flush-headingTwo")%>"  class="nav-link px-0">
        <div class="card h-100">
           <%= cl_image_tag booking.flat.photos.first.key, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to booking.flat.name, flat_path(booking.flat) %></h5>
            <p class="card-text text-truncate"><%= booking.flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= booking.flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{booking.flat.price_per_night} €" %></p>
              <p><%= booking.flat.average_rating %></p>
            </li>
          </ul>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Booking confirmed: <%= booking.confirmed  ? 'yes' : 'no' %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p>Total: <%= "#{booking.total_price} €" %></p>
              <p>von <%= booking.start_date %></p>
              <p>bis<%= booking.end_date %></p>
            </li>
          </ul>
        </div>
        </a>
      </div>
    <% end %>
  </div>
  <% else %>
    <p>no bookings</p>
  <% end %>
</div>

app/views/users/_bookingcardhist.html.erb
<div class="container">
<p>historic bookings:</p>
  <% if @bookings_historic_exist %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
    <% @bookings_historic.each do |booking| %>
      <div class="col">
        <a href="<%= user_booking_path(@user, booking, redir_param: 22, accord_param: "flush-headingTwo")%>"  class="nav-link px-0">
        <div class="card h-100">
          <%= cl_image_tag booking.flat.photos.first.key, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to booking.flat.name, flat_path(booking.flat) %></h5>
            <p class="card-text text-truncate"><%= booking.flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= booking.flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{booking.flat.price_per_night} €" %></p>
              <p><%= booking.flat.average_rating %></p>
            </li>
          </ul>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Booking confirmed: <%= booking.confirmed  ? 'yes' : 'no' %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p>Total: <%= "#{booking.total_price} €" %></p>
              <p>von <%= booking.start_date %></p>
              <p>bis<%= booking.end_date %></p>
            </li>
          </ul>
        </div>
        </a>
      </div>
    <% end %>
  </div>
    <% else %>
    <p>no bookings</p>
  <% end %>
</div>

app/views/users/_hostbookings.html.erb
<div class="container">
<p>current orders:</p>
  <% if @orders_current_exist %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
     <% @orders_current.each do |booking| %>
      <div class="col">
      <a href="<%= user_booking_path( @user, booking, redir_param: 61, accord_param: "flush-headingTwo")%>"  class="nav-link px-0">
        <div class="card h-100">
          <%= cl_image_tag booking.flat.photos.first.key, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to booking.flat.name, flat_path(booking.flat) %></h5>
            <p class="card-text text-truncate"><%= booking.flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= booking.flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{booking.flat.price_per_night} €" %></p>
              <p><%= booking.flat.average_rating %></p>
            </li>
          </ul>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Booking confirmed: <%= booking.confirmed  ? 'yes' : 'no' %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p>Total: <%= "#{booking.total_price} €" %></p>
              <p>von <%= booking.start_date %></p>
              <p>bis<%= booking.end_date %></p>
            </li>
          </ul>
        </div>
        </a>
      </div>
    <% end %>
  </div>
  <% else %>
  <p>no orders</p>
  <% end %>
</div>

app/views/users/_hostbookingshist.html.erb
<div class="container">
<p>historic orders:</p>
 <% if @orders_historic_exist %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <!--CARD ITERATION -->
     <% @orders_historic.each do |booking| %>
      <div class="col">
      <a href="<%= user_booking_path( @user, booking, redir_param: 62, accord_param: "flush-headingTwo")%>"  class="nav-link px-0">
        <div class="card h-100">
          <%= cl_image_tag booking.flat.photos.first.key, class: "card-img-top", alt: "flat picture" %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to booking.flat.name, flat_path(booking.flat) %></h5>
            <p class="card-text text-truncate"><%= booking.flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= booking.flat.location %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p><%= "#{booking.flat.price_per_night} €" %></p>
              <p><%= booking.flat.average_rating %></p>
            </li>
          </ul>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Booking confirmed: <%= booking.confirmed  ? 'yes' : 'no' %></li>
            <li class="list-group-item d-flex justify-content-between">
              <p>Total: <%= "#{booking.total_price} €" %></p>
              <p>von <%= booking.start_date %></p>
              <p>bis<%= booking.end_date %></p>
            </li>
          </ul>
        </div>
        </a>
      </div>
    <% end %>
  </div>
  <% else %>
  <p>no orders</p>
  <% end %>
</div>

app/views/users/_navbar.html.erb
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-light border border-white rounded">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
              <div class="accordion accordion-flush" id="accordionFlushExample">
                 <%= yield :booker %>
                 <%= yield :host %>
              </div>  
            </div>
            <%= hidden_field_tag 'accId', params[:accord_param] || "flush-headingTwo" %>
            <%= hidden_field_tag 'aHrefId', params[:redir_param] || "link_21" %>
        </div>

app/views/users/show.html.erb
 <div class="container-fluid">
   <div class="row flex-nowrap">
     <!--SIDEBAR -->
     <%# Booker %>
     <% content_for(:booker) { render partial: 'sidebar_booker' } %>
     <%# Host %>
     <% if  (@role == 'Host')%>
     <% content_for(:host) { render partial: 'sidebar_host' } %>
     <% end%>
     <%= render  "navbar" %>
     <!--CONTENT -->
     <div class="col py-3">
       <%# Content area... %>
       <div class="container" style="margin-top: 12px">
          <h1>Hello, <%= @user.name%>!</h1>
          <h2>Our dear <%= @role%></h2>  
       </div>

       <!--CARDS -->
       <div class="container" style="margin-top: 12px">
          <% case  @redir%>
          <% when  21%>
             <%= render "bookingcard" %>
           <% when  22%>
             <%= render "bookingcardhist" %>
           <% when  61%>
             <%= render "hostbookings" %>
           <% when  62%>
             <%= render "hostbookingshist" %>
            <% else %>
             ...
          <% end %>
       </div>
     </div>
  </div>
</div>
  

<!-- end of file -->